// ppt_generator.tool.js
import PptxGenJS from 'pptxgenjs';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PPT_OUTPUT_DIR = path.join(process.cwd(), 'user_files', 'ppts');

// Ensure output directory exists
await fs.mkdir(PPT_OUTPUT_DIR, { recursive: true });

/**
 * Create a PowerPoint presentation from topic and information.
 * @param {string} topic - The presentation title.
 * @param {string} information - The content. Separate slides with '---' on a new line.
 * @param {string} [filename] - Optional filename (without extension). Defaults to 'Presentation'.
 * @param {boolean} [autoOpen=true] - If true, automatically open the file after creation.
 * @returns {Promise<{content: Array}>} MCP tool response.
 */
export async function createPPT({ topic, information, filename = 'Presentation', autoOpen = true }) {
  try {
    // 1. Parse slides: split by '---' lines
    const slidesContent = information.split(/\n\s*---\s*\n/).filter(s => s.trim().length > 0);
    if (slidesContent.length === 0) {
      throw new Error('No content provided. Please supply information for the slides.');
    }

    // 2. Create a new presentation
    const ppt = new PptxGenJS();
    ppt.defineLayout({ name: 'WIDE', width: 13.33, height: 7.5 });
    ppt.layout = 'WIDE';

    // 3. Add title slide
    const titleSlide = ppt.addSlide();
    titleSlide.background = { fill: '4472C4' };
    titleSlide.addText(topic, {
      x: 0.5, y: 1.5, w: '90%', h: 2,
      fontSize: 44,
      color: 'FFFFFF',
      align: 'center',
      fontFace: 'Arial',
      bold: true,
    });
    titleSlide.addText('Generated by MCP Assistant', {
      x: 0.5, y: 4.5, w: '90%', h: 1,
      fontSize: 20,
      color: 'FFFFFF',
      align: 'center',
      fontFace: 'Arial',
    });

    // 4. Add content slides
    slidesContent.forEach((content, index) => {
      const slide = ppt.addSlide();
      const lines = content.split('\n').filter(line => line.trim().length > 0);
      const slideTitle = lines.length > 0 ? lines[0].trim() : `Slide ${index + 1}`;
      const bulletPoints = lines.slice(1).map(line => line.trim()).filter(line => line.length > 0);

      slide.addText(slideTitle, {
        x: 0.5, y: 0.5, w: '90%', h: 1.2,
        fontSize: 28,
        color: '1F4E79',
        bold: true,
        fontFace: 'Arial',
      });

      if (bulletPoints.length > 0) {
        slide.addText(bulletPoints, {
          x: 1.0, y: 2.0, w: '80%', h: 4.5,
          fontSize: 20,
          color: '333333',
          fontFace: 'Arial',
          bullet: true,
          valign: 'top',
        });
      } else {
        slide.addText(content, {
          x: 1.0, y: 2.0, w: '80%', h: 4.5,
          fontSize: 20,
          color: '333333',
          fontFace: 'Arial',
          valign: 'top',
        });
      }

      slide.addText(`Page ${index + 2}`, {
        x: 0.5, y: 7.0, w: '90%', h: 0.5,
        fontSize: 12,
        color: '7F7F7F',
        align: 'right',
        fontFace: 'Arial',
      });
    });

    // 5. Save the file
    const fileBase = filename.replace(/\.[^.]+$/, '');
    const filePath = path.join(PPT_OUTPUT_DIR, `${fileBase}.pptx`);
    await ppt.writeFile({ fileName: filePath });

    console.log(`✅ PPT created: ${filePath}`);

    // 6. Optionally open the file
    if (autoOpen) {
      try {
        const { openFile } = await import('./fileopener.tool.js');
        await openFile(filePath);
      } catch (openErr) {
        console.warn('Could not auto‑open file:', openErr.message);
      }
    }

    return {
      content: [{
        type: 'text',
        text: `✅ **PowerPoint presentation created successfully!**\n\n📁 **File path:** \`${filePath}\`\n📊 **Slides:** ${slidesContent.length + 1}\n\n💡 **Next steps:**\n- To open it, use the \`open_file\` tool with the path above.\n- Or manually navigate to the folder and double‑click the file.`,
      }],
    };
  } catch (error) {
    console.error('PPT generation error:', error);
    return {
      content: [{ type: 'text', text: `❌ **Failed to create PowerPoint:** ${error.message}` }],
      isError: true,
    };
  }
}